/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Cham Kai Ling
 */
public class MainPage extends javax.swing.JFrame {

    private final Login loginWindow;

    public MainPage(Login loginWin) {
        initComponents();
        loginWindow = loginWin;
        StaffPage staffPage = new StaffPage();
        jDesktopPanel.add(staffPage).setVisible(true);
        title.setText("Staff Management");
        usernameTxt.setText(loginWindow.userName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side_pane = new javax.swing.JPanel();
        report_btn = new javax.swing.JPanel();
        ind_r = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        productMng_btn = new javax.swing.JPanel();
        ind_p = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        staffMng_btn = new javax.swing.JPanel();
        ind_s = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        usernameTxt = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jDesktopPanel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane.setBackground(new java.awt.Color(56, 0, 107));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        report_btn.setBackground(new java.awt.Color(56, 0, 107));
        report_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                report_btnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                report_btnMousePressed(evt);
            }
        });

        ind_r.setOpaque(false);
        ind_r.setPreferredSize(new java.awt.Dimension(3, 42));

        javax.swing.GroupLayout ind_rLayout = new javax.swing.GroupLayout(ind_r);
        ind_r.setLayout(ind_rLayout);
        ind_rLayout.setHorizontalGroup(
            ind_rLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_rLayout.setVerticalGroup(
            ind_rLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Summary Report");

        javax.swing.GroupLayout report_btnLayout = new javax.swing.GroupLayout(report_btn);
        report_btn.setLayout(report_btnLayout);
        report_btnLayout.setHorizontalGroup(
            report_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report_btnLayout.createSequentialGroup()
                .addComponent(ind_r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        report_btnLayout.setVerticalGroup(
            report_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_r, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        side_pane.add(report_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 139, -1));

        productMng_btn.setBackground(new java.awt.Color(56, 0, 107));
        productMng_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productMng_btnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                productMng_btnMousePressed(evt);
            }
        });

        ind_p.setOpaque(false);
        ind_p.setPreferredSize(new java.awt.Dimension(3, 42));

        javax.swing.GroupLayout ind_pLayout = new javax.swing.GroupLayout(ind_p);
        ind_p.setLayout(ind_pLayout);
        ind_pLayout.setHorizontalGroup(
            ind_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_pLayout.setVerticalGroup(
            ind_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Product Management");

        javax.swing.GroupLayout productMng_btnLayout = new javax.swing.GroupLayout(productMng_btn);
        productMng_btn.setLayout(productMng_btnLayout);
        productMng_btnLayout.setHorizontalGroup(
            productMng_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productMng_btnLayout.createSequentialGroup()
                .addComponent(ind_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        productMng_btnLayout.setVerticalGroup(
            productMng_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_p, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        side_pane.add(productMng_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 139, -1));

        staffMng_btn.setBackground(new java.awt.Color(85, 0, 163));
        staffMng_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffMng_btnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                staffMng_btnMousePressed(evt);
            }
        });

        ind_s.setPreferredSize(new java.awt.Dimension(3, 42));

        javax.swing.GroupLayout ind_sLayout = new javax.swing.GroupLayout(ind_s);
        ind_s.setLayout(ind_sLayout);
        ind_sLayout.setHorizontalGroup(
            ind_sLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_sLayout.setVerticalGroup(
            ind_sLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Staff Management");

        javax.swing.GroupLayout staffMng_btnLayout = new javax.swing.GroupLayout(staffMng_btn);
        staffMng_btn.setLayout(staffMng_btnLayout);
        staffMng_btnLayout.setHorizontalGroup(
            staffMng_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffMng_btnLayout.createSequentialGroup()
                .addComponent(ind_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        staffMng_btnLayout.setVerticalGroup(
            staffMng_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_s, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        side_pane.add(staffMng_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PIZZA");
        side_pane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 42));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FAMILY ");
        side_pane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 42));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jLabel4.setText("LOGOUT");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        side_pane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 90, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        side_pane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 10));

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 570));

        jPanel2.setBackground(new java.awt.Color(106, 27, 154));

        usernameTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        usernameTxt.setForeground(new java.awt.Color(255, 255, 255));
        usernameTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameTxt.setText("Username");

        title.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Staff Management");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 565, Short.MAX_VALUE)
                .addComponent(usernameTxt)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title)
                    .addComponent(usernameTxt))
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 840, 50));

        jDesktopPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPanelLayout = new javax.swing.GroupLayout(jDesktopPanel);
        jDesktopPanel.setLayout(jDesktopPanelLayout);
        jDesktopPanelLayout.setHorizontalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jDesktopPanelLayout.setVerticalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 840, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void staffMng_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffMng_btnMousePressed
        staffMng_btn.setBackground(new Color(85, 0, 163));
        productMng_btn.setBackground(new Color(56, 0, 107));
        report_btn.setBackground(new Color(56, 0, 107));

        ind_s.setOpaque(true);
        ind_p.setOpaque(false);
        ind_r.setOpaque(false);


    }//GEN-LAST:event_staffMng_btnMousePressed

    private void productMng_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productMng_btnMousePressed
        productMng_btn.setBackground(new Color(85, 0, 163));
        staffMng_btn.setBackground(new Color(56, 0, 107));
        report_btn.setBackground(new Color(56, 0, 107));

        ind_p.setOpaque(true);
        ind_r.setOpaque(false);
        ind_s.setOpaque(false);
        title.setText("Product Management");

    }//GEN-LAST:event_productMng_btnMousePressed

    private void report_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_report_btnMousePressed
        report_btn.setBackground(new Color(85, 0, 163));
        staffMng_btn.setBackground(new Color(56, 0, 107));
        productMng_btn.setBackground(new Color(56, 0, 107));
        ind_r.setOpaque(true);
        ind_p.setOpaque(false);
        ind_s.setOpaque(false);
        title.setText("Summary Report");
    }//GEN-LAST:event_report_btnMousePressed

    private void staffMng_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffMng_btnMouseClicked
        StaffPage staffPage = new StaffPage();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(staffPage).setVisible(true);
    }//GEN-LAST:event_staffMng_btnMouseClicked

    private void productMng_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productMng_btnMouseClicked
        ProductPage productPage = new ProductPage();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(productPage).setVisible(true);
    }//GEN-LAST:event_productMng_btnMouseClicked

    private void report_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_report_btnMouseClicked
        ReportPage reportPage = new ReportPage();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(reportPage).setVisible(true);
    }//GEN-LAST:event_report_btnMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        int option = JOptionPane.showConfirmDialog(null, "Do you want to logout ?", "Logout",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
            this.dispose();
            Login loginForm = new Login();
            loginForm.setVisible(true);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login loginWindow = new Login();
                new MainPage(loginWindow).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ind_p;
    private javax.swing.JPanel ind_r;
    private javax.swing.JPanel ind_s;
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel productMng_btn;
    private javax.swing.JPanel report_btn;
    private javax.swing.JPanel side_pane;
    private javax.swing.JPanel staffMng_btn;
    private javax.swing.JLabel title;
    private javax.swing.JLabel usernameTxt;
    // End of variables declaration//GEN-END:variables
}
